import { useEffect, useMemo, useState } from "react";
import { ApprovalStatus, Snapshot, bridge } from "./lib/workbench";

type Page = "desk" | "data" | "evidence" | "review" | "trace" | "settings";
const pages: Array<[Page, string, string]> = [["desk", "01", "Research Desk"], ["data", "02", "Data Bench"], ["evidence", "03", "Evidence Ledger"], ["review", "04", "Review Queue"], ["trace", "05", "Run Trace"], ["settings", "06", "Settings"]];

export default function App() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [page, setPage] = useState<Page>("desk");
  const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { bridge.load().then(setSnapshot).catch((error: unknown) => setNotice(String(error))); }, []);
  const pending = useMemo(() => snapshot?.approvals.filter((item) => item.status === "pending").length ?? 0, [snapshot]);
  if (!snapshot) return <main className="loading"><div className="mark">DF</div><p>Opening governed workbench…</p></main>;
  const resolve = async (id: string, approve: boolean) => { setSnapshot(await bridge.resolve(snapshot, id, approve)); setNotice(approve ? "Approval receipt recorded. External action remains disabled in demo mode." : "Request rejected. The action remains blocked for this run."); };
  const title = pages.find(([id]) => id === page)?.[2] ?? "Workbench";
  return <div className="app"><aside className="rail"><div className="brand"><div className="mark">DF</div><div><b>DataForge</b><span>WORKBENCH</span></div></div><div className="workspace"><i></i><div><small>LOCAL WORKSPACE</small><strong>{snapshot.workspace_label}</strong></div></div><nav>{pages.map(([id, number, label]) => <button key={id} className={page === id ? "active" : ""} onClick={() => setPage(id)}><span>{number}</span>{label}{id === "review" && pending > 0 && <em>{pending}</em>}</button>)}</nav><footer><label>LOCAL-ONLY DEFAULT</label><p>Data and evidence remain in the selected workspace until you approve an export or connector action.</p></footer></aside><main className="stage"><header><div><p>RUN / {snapshot.run_id} <i>•</i> {snapshot.status.replaceAll("_", " ")}</p><h1>{title}</h1></div><div className="header-tools"><div className="budget"><small>RUN BUDGET</small><b>{snapshot.budget.model_turns_used}/{snapshot.budget.model_turn_limit} turns</b><span>{snapshot.budget.tool_calls_used}/{snapshot.budget.tool_call_limit} tools</span></div><button className="new" onClick={() => setNotice("New-run intake opens after the current review is resolved. This release prevents overlapping run state.")}>+ New run</button></div></header>{notice && <div className="notice">● {notice}<button onClick={() => setNotice(null)}>Dismiss</button></div>}{page === "desk" && <Desk snapshot={snapshot} review={() => setPage("review")} />}{page === "data" && <Data snapshot={snapshot} />}{page === "evidence" && <Evidence snapshot={snapshot} />}{page === "review" && <Review snapshot={snapshot} resolve={resolve} />}{page === "trace" && <Trace snapshot={snapshot} />}{page === "settings" && <Settings />}</main></div>;
}

function Desk({ snapshot, review }: { snapshot: Snapshot; review: () => void }) { return <section className="desk grid"><article className="brief card"><small>CURRENT BRIEF <b>GOVERNED</b></small><h2>{snapshot.question}</h2><p className="classification">CLASSIFICATION <span>{snapshot.classification}</span></p><div className="brief-meta"><div><small>Active specialist</small><strong>Research planner</strong></div><div><small>Outbound status</small><strong className="amber">Held for review</strong></div><button onClick={review}>Open review queue →</button></div></article><article className="readiness card"><small>RUN READINESS</small><div className="dial"><b>62</b><span>%</span></div><p>Local evidence is ready. Public context is paused at the approval boundary.</p><label><i></i>Local verified <i className="amber-dot"></i>Review held</label></article><article className="graph card"><small>WORK GRAPH <b>{snapshot.work_items.length} stages</b></small><div className="nodes">{snapshot.work_items.map((item, index) => <div className={item.status} key={item.id}><span>{String(index + 1).padStart(2, "0")}</span><i></i><strong>{item.title}</strong><p>{item.specialist}</p></div>)}</div></article><article className="guard card"><div><small>ACTIVE GUARD</small><h3>No silent external research</h3><p>The proposed public query is redacted and awaiting a scoped operator decision.</p></div><b>HOLD</b></article></section>; }
function Data({ snapshot }: { snapshot: Snapshot }) { return <section className="data grid"><article className="card profile"><small>LOCAL PROFILING BENCH <b>READ ONLY</b></small><h2>Aggregate quality pass</h2><div className="metrics"><Metric value="47" label="fields observed"/><Metric value="8.8%" label="largest null rate"/><Metric value="3" label="unit families"/></div><div className="sparks"><Spark label="Temporal coverage" values={[30,42,54,42,77,64,84,75,92]}/><Spark label="Completeness" values={[86,90,88,92,76,91,94,87,93]}/></div></article><article className="card gates"><small>QUALITY GATES</small>{snapshot.work_items.slice(0,3).map((item) => <div key={item.id}><i className={item.status}></i><p><strong>{item.title}</strong><span>{item.detail}</span></p><em>{item.risk}</em></div>)}</article><article className="card preview"><small>SAFE PREVIEW</small><pre>{`field                 type       decision\nobserved_at           timestamp  retain\nsource_unit           enum       reconcile\naggregate_metric      number     retain\nrecord_identifier     string     redact\nfree_text             string     not displayed`}</pre><p>Only display-safe metadata is rendered in this preview.</p></article></section>; }
function Evidence({ snapshot }: { snapshot: Snapshot }) { return <section className="ledger"><div className="section-head"><div><small>EVIDENCE LEDGER</small><h2>Claims stay attached to receipts.</h2></div><b>{snapshot.evidence.length} local receipts</b></div>{snapshot.evidence.map((item) => <article className="receipt" key={item.id}><i>⌁</i><div><h3>{item.label} <span>{item.source}</span></h3><p>{item.claim}</p><em>{item.redaction_note}</em></div><aside><b>{item.verification}</b><span>{item.captured_at}</span><code>sha256:{item.digest}</code></aside></article>)}</section>; }
function Review({ snapshot, resolve }: { snapshot: Snapshot; resolve: (id: string, approve: boolean) => void }) { return <section className="review"><article className="review-intro card"><div><small>HUMAN REVIEW REQUIRED</small><h2>Scoped decisions, not blanket trust.</h2><p>Approval activates only the listed action and expires automatically. It does not grant filesystem, credential, export, or publication access.</p></div><b>OPERATOR<br/>GATE</b></article>{snapshot.approvals.map((item) => <article className={`approval card ${item.status}`} key={item.id}><div className="approval-head"><div><small>{item.action}</small><h3>{item.specialist} requests a constrained action</h3></div><b>{item.status}</b></div><div className="approval-body"><p><small>TARGET PREVIEW</small>{item.target_preview}</p><p><small>RATIONALE</small>{item.rationale}</p></div><div className="scopes">{item.scope.map((scope) => <span key={scope}>{scope}</span>)}</div><footer><em>{item.expires_at}</em>{item.status === "pending" ? <div><button onClick={() => resolve(item.id, false)}>Reject</button><button className="approve" onClick={() => resolve(item.id, true)}>Approve scope</button></div> : <strong>{item.status === "approved" ? "Receipt recorded — external action remains disabled in demo mode." : "Rejected target retained in current run memory."}</strong>}</footer></article>)}</section>; }
function Trace({ snapshot }: { snapshot: Snapshot }) { return <section className="trace"><article className="trace-intro card"><small>REPLAYABLE RUN TRACE</small><h2>Every decision leaves a local mark.</h2><p>Plan, tool, observation, interpretation, and review events remain ordered for verification and export review.</p></article><div className="timeline">{snapshot.trace.map((item) => <article className={item.state} key={item.id}><time>{item.at}</time><span>{item.category}</span><div><h3>{item.title}</h3><p>{item.detail}</p></div></article>)}</div><article className="policy card"><small>EXECUTION POLICY</small><p>Local work can progress inside budget. External, destructive, or consequential work stops at a scope-bound approval receipt.</p><code>run epoch: {snapshot.run_id}<br/>mode: local-first / no background polling</code></article></section>; }
function Settings() { return <section className="settings grid"><article className="card"><small>LOCAL HOST</small><h2>{bridge.native() ? "Desktop bridge connected" : "Browser demo bridge active"}</h2><p>The renderer can request only typed snapshot and approval commands. Arbitrary paths, network targets, and provider secrets are unavailable to the interface.</p><Rules rows={[["Filesystem", "Selected workspace only"], ["Network", "Disabled until approval"], ["Secrets", "Never rendered in UI"]]}/></article><article className="card"><small>RUN DEFAULTS</small><h2>Bounded autonomy</h2><Rules rows={[["Model turns", "8 per run"], ["Tool calls", "12 per run"], ["Approval lifetime", "Scoped and expiring"]]}/><p className="warning">Unrestricted execution, background polling, and bypass paths are intentionally absent.</p></article></section>; }
function Metric({ value, label }: { value: string; label: string }) { return <div><b>{value}</b><span>{label}</span></div>; }
function Spark({ label, values }: { label: string; values: number[] }) { return <div><p>{label}<b>LOCAL</b></p><aside>{values.map((value, index) => <i key={index} style={{height:`${value}%`}} />)}</aside></div>; }
function Rules({ rows }: { rows: string[][] }) { return <div className="rules">{rows.map(([label, value]) => <p key={label}><span>{label}</span><b>{value}</b></p>)}</div>; }
